// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/ProtoDef.proto

#ifndef PROTOBUF_src_2fprotobuf_2fProtoDef_2eproto__INCLUDED
#define PROTOBUF_src_2fprotobuf_2fProtoDef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ProtoDef {
class RpcPo;
class RpcPoDefaultTypeInternal;
extern RpcPoDefaultTypeInternal _RpcPo_default_instance_;
}  // namespace ProtoDef

namespace ProtoDef {

namespace protobuf_src_2fprotobuf_2fProtoDef_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_src_2fprotobuf_2fProtoDef_2eproto

// ===================================================================

class RpcPo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoDef.RpcPo) */ {
 public:
  RpcPo();
  virtual ~RpcPo();

  RpcPo(const RpcPo& from);

  inline RpcPo& operator=(const RpcPo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RpcPo& default_instance();

  static inline const RpcPo* internal_default_instance() {
    return reinterpret_cast<const RpcPo*>(
               &_RpcPo_default_instance_);
  }

  void Swap(RpcPo* other);

  // implements Message ----------------------------------------------

  inline RpcPo* New() const PROTOBUF_FINAL { return New(NULL); }

  RpcPo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RpcPo& from);
  void MergeFrom(const RpcPo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RpcPo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string rpc = 1;
  void clear_rpc();
  static const int kRpcFieldNumber = 1;
  const ::std::string& rpc() const;
  void set_rpc(const ::std::string& value);
  #if LANG_CXX11
  void set_rpc(::std::string&& value);
  #endif
  void set_rpc(const char* value);
  void set_rpc(const char* value, size_t size);
  ::std::string* mutable_rpc();
  ::std::string* release_rpc();
  void set_allocated_rpc(::std::string* rpc);

  // bytes anyPo = 2;
  void clear_anypo();
  static const int kAnyPoFieldNumber = 2;
  const ::std::string& anypo() const;
  void set_anypo(const ::std::string& value);
  #if LANG_CXX11
  void set_anypo(::std::string&& value);
  #endif
  void set_anypo(const char* value);
  void set_anypo(const void* value, size_t size);
  ::std::string* mutable_anypo();
  ::std::string* release_anypo();
  void set_allocated_anypo(::std::string* anypo);

  // @@protoc_insertion_point(class_scope:ProtoDef.RpcPo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr rpc_;
  ::google::protobuf::internal::ArenaStringPtr anypo_;
  mutable int _cached_size_;
  friend struct  protobuf_src_2fprotobuf_2fProtoDef_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcPo

// string rpc = 1;
inline void RpcPo::clear_rpc() {
  rpc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RpcPo::rpc() const {
  // @@protoc_insertion_point(field_get:ProtoDef.RpcPo.rpc)
  return rpc_.GetNoArena();
}
inline void RpcPo::set_rpc(const ::std::string& value) {
  
  rpc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ProtoDef.RpcPo.rpc)
}
#if LANG_CXX11
inline void RpcPo::set_rpc(::std::string&& value) {
  
  rpc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ProtoDef.RpcPo.rpc)
}
#endif
inline void RpcPo::set_rpc(const char* value) {
  
  rpc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ProtoDef.RpcPo.rpc)
}
inline void RpcPo::set_rpc(const char* value, size_t size) {
  
  rpc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ProtoDef.RpcPo.rpc)
}
inline ::std::string* RpcPo::mutable_rpc() {
  
  // @@protoc_insertion_point(field_mutable:ProtoDef.RpcPo.rpc)
  return rpc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RpcPo::release_rpc() {
  // @@protoc_insertion_point(field_release:ProtoDef.RpcPo.rpc)
  
  return rpc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RpcPo::set_allocated_rpc(::std::string* rpc) {
  if (rpc != NULL) {
    
  } else {
    
  }
  rpc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rpc);
  // @@protoc_insertion_point(field_set_allocated:ProtoDef.RpcPo.rpc)
}

// bytes anyPo = 2;
inline void RpcPo::clear_anypo() {
  anypo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RpcPo::anypo() const {
  // @@protoc_insertion_point(field_get:ProtoDef.RpcPo.anyPo)
  return anypo_.GetNoArena();
}
inline void RpcPo::set_anypo(const ::std::string& value) {
  
  anypo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ProtoDef.RpcPo.anyPo)
}
#if LANG_CXX11
inline void RpcPo::set_anypo(::std::string&& value) {
  
  anypo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ProtoDef.RpcPo.anyPo)
}
#endif
inline void RpcPo::set_anypo(const char* value) {
  
  anypo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ProtoDef.RpcPo.anyPo)
}
inline void RpcPo::set_anypo(const void* value, size_t size) {
  
  anypo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ProtoDef.RpcPo.anyPo)
}
inline ::std::string* RpcPo::mutable_anypo() {
  
  // @@protoc_insertion_point(field_mutable:ProtoDef.RpcPo.anyPo)
  return anypo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RpcPo::release_anypo() {
  // @@protoc_insertion_point(field_release:ProtoDef.RpcPo.anyPo)
  
  return anypo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RpcPo::set_allocated_anypo(::std::string* anypo) {
  if (anypo != NULL) {
    
  } else {
    
  }
  anypo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), anypo);
  // @@protoc_insertion_point(field_set_allocated:ProtoDef.RpcPo.anyPo)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace ProtoDef

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_2fprotobuf_2fProtoDef_2eproto__INCLUDED
